<?php echo '<?xml version="1.0" encoding="UTF-8"?>' ?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>{{ url('/article') }}</loc>
        <changefreq>daily</changefreq>
        <priority>1.0</priority>
    </url>
    @foreach($blogs as $blog)
        <url>
            <loc>{{ url('article/' . $blog->slug) }}</loc>
            <lastmod>{{ gmdate(DateTime::W3C, strtotime($blog->updated_at)) }}</lastmod>
            <changefreq>daily</changefreq>
            <priority>1.0</priority>
        </url>
    @endforeach
</urlset>
<!-- XML Sitemap generated by Algoflow SEO -->
