<?php echo '<?xml version="1.0" encoding="UTF-8"?>' ?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>{{ url('clinics/') }}</loc>
        <lastmod>{{ gmdate(DateTime::W3C, strtotime(Date::now()->format('Y-m-d his'))) }}</lastmod>
        <changefreq>daily</changefreq>
        <priority>1.0</priority>
    </url>
    @foreach($clinics as $clinic)
        <url>
            <loc>{{ url('clinic/' . $clinic->clinic_slug) }}</loc>
            <lastmod>{{ gmdate(DateTime::W3C, strtotime($clinic->updated_at)) }}</lastmod>
            <changefreq>daily</changefreq>
            <priority>1.0</priority>
        </url>
    @endforeach
</urlset>
<!-- XML Sitemap generated by Algoflow SEO -->
