<?php echo '<?xml version="1.0" encoding="UTF-8"?>' ?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>
        <loc>{{ url('page_sitemap.xml') }}</loc>
        <lastmod>{{date("Y-m-d\Th:m:s+00:00")}}</lastmod>
    </sitemap>
    <sitemap>
        <loc>{{ url('article_sitemap.xml') }}</loc>
        <lastmod>{{ date("Y-m-d\Th:m:s+00:00") }}</lastmod>
    </sitemap>
    <sitemap>
        <loc>{{ url('location_sitemap.xml') }}</loc>
        <lastmod>{{date("Y-m-d\Th:m:s+00:00")}}</lastmod>
    </sitemap>
</sitemapindex>
<!-- XML Sitemap generated by Algoflow SEO -->
